### ISSUE TITLE
adding languages

### ISSUE THREAD

**Issue by Josverl** [semeif/TRSsetup#1]
Happy to add a translation to Dutch to this :-) 

what is the best way to do that ?

**Comment by semeif** [comment]
Hi Jos, sorry for getting back so late. You can clone this repo and push it to your account. Then you need add after each "if ($Language - eq "de-DE") {...} an elseif ($Language -eq "nl-NL") {....}

..
if ($Language -eq "de-DE") 
 {   
 Write-Host $Text25Stars   
 Write-Host '*Möchten Sie mit der MTR*'   
 Write-Host '* Einrichtung starten?  *'     
Write-Host $Text25Stars  
}  
**elseif ($Language -eq "nl-NL")
{
 Write-Host $Text25Stars   
 Write-Host '*Wilt u beginnen *'   
 Write-Host '* met de MTR setup?  *'     
Write-Host $Text25Stars  
}**
else 
{   
 Write-Host $Text25Stars    
Write-Host '* Do you want to start  *'   
 Write-Host '*    the MTR setup?     *'     
Write-Host $Text25Stars   }
...

Cheers,
Frank&Sebastian

**Comment by semeif** [comment]
@Josverl will do the NL translation. (●'◡'●)
